# Generated by Django 2.2.24 on 2021-07-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookpage', '0003_auto_20210704_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='manga_id',
            new_name='isbn',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='tag',
        ),
        migrations.AddField(
            model_name='manga',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='isbn',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='manga',
            name='publisher_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
